### ISSUE TITLE
Create/Update with an instructor that does not exist or no instructors

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms-rest#129]
While writing the memberships API, I wondered if the results of the following tests are correct.
@thomasplevy & @eri-trabiccolo, What should the result of the following tests be? 

### Tests

1. Create membership with non-existing instructor.
instructors = current user
2. Create membership with one instructor that exists and one that does not.
instructors = existing instructor
3. Update membership with non-existing instructor.
instructors = original instructor
4. Update membership with one instructor that exists and one that does not.
instructors = existing instructor
5. Create membership with empty instructors array.
instructors = current user
6. Update membership with empty instructors array.
instructors = original instructor

`llms_validate_instructors()` in pull #98 causes `400 Bad Request` to be returned for all of these tests.

**Comment by eri-trabiccolo** [comment]
My idea is that if you don't provide any instructors on creation then the author will be set as instructor as fall back.

But if you provide a list (included an empty list) of instructors it has to be a valid list of users that are instructors: mimicking the wp admin where you can select the instructor only from a list of actual instructors.

IMHO at maximum we can allow providing an empty list that will mean "reset the course/membership instructors" so set the instructor to the post author.

**Comment by thomasplevy** [comment]
You should *not* be able to *create* instructors through a membership / course create/update requests.

I agree with @eri-trabiccolo 

If you send through a list of instructors it should be validated and if it contains any invalid instructors an error should be returned. If there's even a single invalid instructor in that list it should return an error denoting that instructors must be valid.

The spec currently notes the list must be "non-empty" which would prevent us from emptying the the instructor list. While we do have functionality in the core codebase to "empty and reset to the post_author" this is basically WP Editor compatibility code which I don't think makes sense to mimic in the REST API. Especially since we are not exposing "post_author" as a field managed by the LifterLMS REST API.

So if you wish to "reset" to the post author I think that should be accomplished by a POST request with a single ID of the sole instructor you'd like to become the instructor.

Also: I've been holding on #98 because it's wrapped up in LifterLMS Blocks functionality that hasn't been released in the LifterLMS Core yet. When that's released I'll merge #98 in.
