### ISSUE TITLE
Tests failing on PHP 7.4.

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#147]
As far as I can tell (from physical usage of the REST API locally on a 7.4 env) the api itself functions just fine but the tests are failing on 7.4

See CircleCI output of the latest set of tests: https://app.circleci.com/jobs/github/gocodebox/lifterlms-rest/1318

**Comment by eri-trabiccolo** [comment]
This seems to be due to wp using functions deprecated in PHP 7.4.
I've been able to reproduce this locally. Well actually I get a lot more errors all seems to stem from:
`PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/www/wordpress-trunk/public_html/src/wp-includes/formatting.php on line 4769
`
or similar.

**Comment by thomasplevy** [comment]
I think we accidentally on purpose fixed this. Latest tests ran without issue. Closing.
