### ISSUE TITLE
Courses: specs miss some properties

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#16]
yes|no properties:
- (access) time_period  (string)  Whether or not a course time period restriction is enabled [yes|no] (all checks should check for 'yes' as an empty string might be returned)
- enrollment_period  (string)  Whether or not a course time period restriction is enabled [yes|no] (all checks should check for 'yes' as an empty string might be returned)
- has_prerequisite   (string)  Determine if prerequisites are enabled [yes|no]
- tile_featured_video (string)  Displays the featured video instead of the featured image on course tiles [yes|no]

others:
- average_grade  (float)  Calculated value of the overall average grade of all *enrolled* students in the course.
- average_progress  (float)  Calculated value of the overall average progress of all *enrolled* students in the course.

**Comment by thomasplevy** [comment]
The existence of these yes/no fields exist mostly to facilitate the UI on the course options metabox however they are not actually necessary/are redundant via the rest api.

For example, if both access time period dates fields are empty then the existing access_time_period property can be flipped to `no`, likewise if at least one exists then it can be flipped to `yes`. My goal is actually to phase these properties out all together in the future but for backwards compatibility purposes the rest api create and update methods can interpret these values instead of requiring them to be submitted.

the `average_grade` and `average_progress` properties exist to cache data and facilitate some reporting screens. These are properties that can be safely ignored on the course resource level even though they currently exist on the `LLMS_Course` model

Grading and progress data will be returned by the `/reports` resource (see #1).

**Comment by eri-trabiccolo** [comment]
I see what you mean.
Though about this
> The existence of these yes/no fields exist mostly to facilitate the UI on the course options metabox however they are not actually necessary/are redundant via the rest api.
> 
> For example, if both access time period dates fields are empty then the existing access_time_period property can be flipped to `no`, likewise if at least one exists then it can be flipped to `yes`. My goal is actually to phase these properties out all together in the future but for backwards compatibility purposes the rest api create and update methods can interpret these values instead of requiring them to be submitted.

I was thinking about this case (editing the course via admin UI): one sets the access time period to on, then sets some start and end dates and saves, then decides to set the access time period to off, and this is possible because the UI allows it. Dates are still set, but the user still doesn't want to have a limited access period, and this is something that a rest API consumer, should be able to know... Am I wrong? Possibly I'm missing something.

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

Yea I guess you're right... I don't like the existing schema on the course model. It feels like there's just way too many unnecessary properties for things that we don't need a set of properties for.

My issue here is that in order to manage these fields via the REST api you'll need to set two properties.

Given the capabilites of the OAPI spec and the resulting interface there's no way to mark a property as *conditionally required*.

I'm thinking that having to set TWO PROPERTIES in order to turn this on is not going to be explicitly clear. So I'm trying to do away with them.

Maybe a better way to do this would be to update the current metabox to no longer rely on these fields to determine the status. Turning the toggle to "no" to turn the access period off will not save a value but instead *clear the dates*.

Then we can simply do away with the yes/no fields entirely.

I *really do not want to add these fields to the rest api schema if possible*.

What do you think?

**Comment by eri-trabiccolo** [comment]
Yeah that makes sense, the only "problem" would be with legacy data when the "no" didn't clear dates, but we can always create db update routines, right?!

**Comment by thomasplevy** [comment]
Yea, a simple db update could take care of that pretty easily, do you think this makes sense as a path forward, am I being too willfull?

I'll open  an issue in core if you don't have any other arguments

**Comment by eri-trabiccolo** [comment]
I think it's fine but it's 23:20 here so you know... I'm sleepy eheh.
With the "new" way I think we don't introduce any real regression except for those who might want to set now a limit "for the future" but they want to activate it when more near the starting date (does it make sense?). But I think it's not that common plus... hey I don't think covering every weird use case would be a good designing pattern :)

**Comment by eri-trabiccolo** [comment]
I guess that also the [recently added](https://github.com/gocodebox/lifterlms-rest/commit/7b9712b6cccd1371ec810ccd02c3345b6f58c703#diff-f438ec0990118ddfa46daae2716d8ff2R67) `capacity_enabled` prop will be removed.
If not, let's fix the typo (`capacaity`) :D

**Comment by eri-trabiccolo** [comment]
> I guess that also the [recently added](https://github.com/gocodebox/lifterlms-rest/commit/7b9712b6cccd1371ec810ccd02c3345b6f58c703#diff-f438ec0990118ddfa46daae2716d8ff2R67) `capacity_enabled` prop will be removed.
> If not, let's fix the typo (`capacaity`) :D

`capacity_enabled` will be not removed because, Thomas says:

> I left the `capacity_enable` to be able to differentiate between 0 capacity and on capacity

**Comment by thomasplevy** [comment]
Updated typo, will deploy later

**Comment by thomasplevy** [comment]
Closing this issue. Any additional properties we need to add please open a new issue

**Comment by eri-trabiccolo** [comment]
> Yea, a simple db update could take care of that pretty easily, do you think this makes sense as a path forward, am I being too willfull?
> 
> I'll open an issue in core if you don't have any other arguments

Do you want me opening an issue in core?

**Comment by thomasplevy** [comment]
Yes
