### ISSUE TITLE
Course _links['enrollments']['href'] should be /wp-json/llms/v1/courses/1234/enrollment

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#21]
while it's still `/wp-json/llms/v1/enrollments?post=1234`

**Comment by eri-trabiccolo** [comment]
Actually no,
according to:
https://github.com/gocodebox/lifterlms-rest/issues/1#issue-446852678
this is correct but I'm confused because I don't see the Enrollments resource spec out here:
https://gocodebox.github.io/lifterlms-rest/

**Comment by thomasplevy** [comment]
@eri-trabiccolo you're initial report is correct.

I removed `enrollments` as a top-level resource as having it there requires each enrollment to have it's own unique ID (which is not how LifterLMS currently functions).

It has, instead, been moved to be below students `[students/1234/enrollments](https://gocodebox.github.io/lifterlms-rest/#tag/Student-Enrollments)` so that each enrollment will be referenced by the student id and the post id of the enrollment.

Adding the listing function for enrollments below courses and memberships will make easy to pull student lists by course and having it under `students` will make it easy to pull a list of a student's enrollments.

If you want to actually preform an enrollment (add a student to a course or membership) you'll have both the post id and the student id and can do so via the `POST /students/{id}/enrollments`

Does that make sense?

**Comment by thomasplevy** [comment]
Updated the spec, if you're happy with my explanation and thinking here please close the issue

**Comment by eri-trabiccolo** [comment]
Yes thanks, it makes sense.
I knew you removed `enrollments` as a top-level resource, you actually told me when you did it, that's why I was confidente I had to open this issue. But then I checked #1 again and saw that
> Course Enrollments ~/courses/{id}/enrollments~ /enrollments?post={id}

so I started to doubt of my understanding :D 
Maybe we need to update #1 as well?

I'm closing this.

**Comment by thomasplevy** [comment]
Oh yea, okay, updated #1 to reflect current state
