### ISSUE TITLE
Resource: Sections

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#30]
- [x] [List](https://gocodebox.github.io/lifterlms-rest/#tag/Sections/paths/~1sections/get)
- [ ] [Create](https://gocodebox.github.io/lifterlms-rest/#tag/Sections/paths/~1sections/post)
- [x] [Retrieve](https://gocodebox.github.io/lifterlms-rest/#tag/Sections/paths/~1sections~1{id}/get)
- [ ] [Update](https://gocodebox.github.io/lifterlms-rest/#tag/Sections/paths/~1sections~1{id}/post)
- [x] [Delete](https://gocodebox.github.io/lifterlms-rest/#tag/Sections/paths/~1sections~1{id}/delete)
- [x] [List Content](https://gocodebox.github.io/lifterlms-rest/#tag/Sections/paths/~1sections~1{id}~1content/get)
- [x] Test Coverage 90% or greater

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I'm finishing this...
Do you think that, when creating/updating a section we should avoid having sections with the same order? Meaning add some logic to "auto-increment" the `order` property?

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

>Do you think that, when creating/updating a section we should avoid having sections with the same order? Meaning add some logic to "auto-increment" the order property?

Yes... we should.

I'm not entirely certain the best way to do this is.... Since we'll always have a "parent_id" for the course, the *default* value could be to push it to the end of the course. Preform a lookup for the last section's order and add one to it...

It gets more complicated when updating a section though.... What should happen if you update with an order that already exists? Should it be incremented and put after the existing section. Then should all the other sections bump up by one also during the update? Then we start to semantically break things by allowing a resource to affect other resources..

I don't know... Do you have any thoughts for good strategies here?

**Comment by eri-trabiccolo** [comment]
Yeah complicated, nope I have no thoughts for good strategies here at the moment.
I see how "ordering" sections might be complicated with the current api.

**Comment by eri-trabiccolo** [comment]
Create and Update checklist items are not completed because of the auto-increment issue discussed above.

**Comment by thomasplevy** [comment]
I've been thinking (and reading) about this design problem and I think we need to adjust the way this is handled all together. This should also apply to all our resources with a structured order property (sections, lessons, questions, etc...).

1) The "order" property should become read only
2) A new resource will always be auto-incremented and dropped to the end of the list (this will have to be a function of our controllers and be known to consumers).
3) New `PATCH` endpoints should be created for each resource list that allows updating this list of resources.

This new endpoints could look something like:

PATCH: `/courses/{id}/content`
```json
[ {
   "id": 123,
   "order": 1,
}, {
   "id": 456,
   "order": 2,
} ]
```

The patch request *must* contain every item that would change in the list. That means if you have 10 sections in a course and you want to move item 1 to item 10 the "order" of every section in the course would change (2-10 all get subtracted by one and 1 changes to 10). That means that patch request should include 10 objects. 

A request to move item 9 to item 10 would then have to include only items 9 and 10:

```json
[ {
   "id": 123,
   "order": 10,
}, {
   "id": 456,
   "order": 9,
} ]
```

This does make *more effort* for the individual consuming the API. Adding a new section to the front of a course now becomes potentially 3 requests:

1) To create the section
2) to get the current list of sections
3) To patch the list to the new order

However, doing it this way will reduce a lot of potential confusion around what's happening when the order is updated.

This changes things to think about the list as its own unique resource which is updated and managed on its own.

Outside of it being a lot of work to write and code do you think this makes sense?

**Comment by eri-trabiccolo** [comment]
I had a similar thought, though less structured eheh.
I thought that the default behavior should have been the auto-increment (which implied making the order read-only) mostly because it made no sense to me that we "arbitrarily" change a property sent by the consumer...
Then I thought that we needed an endpoint (similar to the WooCommerce's "batch") that would allow exactly what you described above. I had not explored that too much, was just a thought in an embryonic stage.
So I agree with your idea. Only need to see if I find technical issues while implementing it, but theoretically it makes sense.

**Comment by thomasplevy** [comment]
Cool. I'll work out a spec for the PATCH endpoint(s) tomorrow.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I think I missed the following part when I replied, probably because you've added it while I was replying, not sure...

> Edit:
> We might also want to think about actually removing the order property from the database in its current form. Instead of having the _llms_order meta property on each child resource the parent resource would have a single property _llms_children which would be an array like the above patch request example.
> 
> Now in the core when we query for sections via the LLMS_Course::get_sections instead of querying by the _llms_parent property for section post types ordered by the _llms_order meta prop we can pull the courses map property, reduce it to an ordered array of section ids and pass that into the include property ordered by the include list.
> 
> If we do this it would significantly reduce the number of writes we'd need to preform during the list patches.

I see.
Does this mean that, in core, you won't be able to set the children order via the children api?
I mean you cannot do `$section->set('order', 2)` anymore?

I'm thinking that moving in the direction you proposed would even make having the same section in multiple courses (and lessons in multiple sections) much more easy (in that case the "parent_id" would be an array of course ids).

Anyway in case we go for this "children" solution I guess this would be a parent property to add (right?), so this is something we have to decide (and implement in core) pretty soon. 

I'm not sure I like this though :D I mean:
We're saying that the `_llms_children` is a course property (and also a course post meta). 
The `parent_id` is a required section's resource property, this means that when creating a new section resource we have to also "modify" its course parent (to update the children list), another resource, and we wanted to avoid this, right?
Should the `parent_id` be read-only as well and we can only set the section's parent by updating the course resource (its children property).

Am I overcomplicating this and we can live with modifying the course resource when creating a section?!  mmm

**Comment by eri-trabiccolo** [comment]
As for #46 we're tracking the `order` issue in
https://github.com/gocodebox/lifterlms-rest/issues/78
