### ISSUE TITLE
Pagination: uniform the way the pagination links are returned so that we can abstract it.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#75]
Compare this:
https://github.com/gocodebox/lifterlms-rest/blob/1.0.0-beta.2/includes/abstracts/class-llms-rest-controller.php#L253-L280

with this:
https://github.com/gocodebox/lifterlms-rest/blob/master/includes/abstracts/class-llms-rest-posts-controller.php#L142-L161

In the first case we return the "first" page link only if the current page is different than 1, and the "last" only if the current page is different than the last page.

In the the second case we always add first and last page even if they match the current page. This second case is the one I've implemented, because I thought first and last were "absolute" concepts not depending on the current page.

What's the desired behavior?

Once this has been abstracted we can abstract the pagination tests as well.

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

Good catch.

> This second case is the one I've implemented, because I thought first and last were "absolute" concepts not depending on the current page.

You are correct that these are absolute but the links themselves are absolute/unchanging however the purpose of the relationship links are to provide consumers with a means to traverse the pages without having to build their own URLs. My thinking is that we should only provide consumers with what they require here and what I mean by that is that if you're currently on the last page _you do not need a link to the last page in order to get to the last page (because you're already there)._ I think this is the same idea as paginating a link list on a series of search results / blog posts / whatever where you'd see:

**(1)** 2 3 Next Last
First Prev 1 **(2)** 3 Next Last
First Prev 1 2 **(3)**

_Bold / parenthesis is the "current" page for the example_

If you think about it that way I don't think it makes sense to always include first and last links.

To help my thinking around this I looked at a few APIs that provide pagination links headers like this (the WP core does not include first/last) so see if there's any unspoken (but common) accepted patterns for this:

GitHub follows this pattern, perform GET requests for the following:

Page 1: https://api.github.com/search/code?q=addClass+user:mozilla -- link includes "Next" and "Last"
Page 2: &page2 -- link includes "first", "prev", "next" and "last"
Page 34 (last page): Link includes "first" and "prev"

**Comment by eri-trabiccolo** [comment]
Makes sense.
So let's uniform to https://github.com/gocodebox/lifterlms-rest/blob/1.0.0-beta.2/includes/abstracts/class-llms-rest-controller.php#L253-L280

**Comment by thomasplevy** [comment]
Sounds good
