### ISSUE TITLE
Properties defined multiple times

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms-rest#91]
In the LifterLMS REST API spec, some schemas end up having properties that are defined multiple times. For example, `#/components/schemas/Course` uses `allOf` to bring in `#/components/schemas/PostPublic`, which defines the `post_type` property, and also to re-define the `post_type` property with a more specific example field. This passes several validator tools that I've used and document viewers like ReDoc and Swagger-UI, but it breaks generator tools, like [NSwag](https://github.com/RicoSuter/NSwag).

It is not clear to me in the [OpenAPI schema object documentation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject) what should happen when a property is defined twice. Should the attributes be merged, which is what we would like to have happen? Is `allOf` only meant to merge **different** properties into a  schema?

If it is determined that properties should only be defined once, then I would be happy to submit a pull request for this issue.

**Comment by thomasplevy** [comment]
@pondermatic 

As far as I've been able to determine it's okay to redefine properties in order to override things that are shared from a schema.

This is not an oversight or a bug on my part. I've done this in order to allow overwriting certain things (such as a description) in the rendered spec.

I don't know about NSwag but I'm concerned with passing the "official" OpenAPI Spec Validators (Swagger).

If we remove the redefinitions the spec rendered documentation changes drastically (you can see it firsthand locally if you want to play with it).

That will cause some confusion when reading the documentation. This is a tool we're using PRIMARILY to create human-readable documentation. If the spec itself is a little dense __I don't care__ because most humans aren't going to be reading it.

ALL OF THAT SAID if there's an actual problem that we should be addressing here I'd like to know what that is but from my perspective it's all okay.

Help me understand what the problem is and why this would be something important for us to change.

**Comment by pondermatic** [comment]
I'm not sure if it's OK to redefine **some** property attributes or if NSwag **should** be handling multiple definitions. I suspect that NSwag is in the wrong here and wanted to get your feedback on it.

I'm going to try the official [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) to see how it handles multiple definitions.

**Comment by pondermatic** [comment]
There is an online version of [Swagger Codegen](https://generator3.swagger.io/ui/). I tested the `POST /generate` operation with the following request body:
```JSON
{
  "lang": "php",
  "specURL": "https://developer.lifterlms.com/rest-api/openapi.json",
  "type": "CLIENT",
  "codegenVersion": "V3"
}
```

The results in `docs/Model` and `lib/Model` files are mixed.
- `default` field uses the extended version. Yay!
- `description` field uses the base version. Boo!
- `example` field is not used.

There may be other fields to examine, but I only looked at properties that NSwag was having problems with: `permalink`, `post_type`, `tags`, `catalog_visibility`, `categories`.

It seems that the OpenAPI specification needs to be clearer about how `allOf` should work. Even the "official" Swagger Codegen's behavior is inconsistent. I suspect that property fields in extended definitions **should** override the base ones, but because it's a pain to implement in generator and visualizer code, it is not always done.

**Comment by thomasplevy** [comment]
@pondermatic 

I'm really not sure if you're looking for me to do anything here...

I'm not sure if I should be trying to fix something that's not entirely clear, especially because for our implementation (using this as a documentation generator) it's not causing any issues that I can find...

If you're just looking to discuss than I'm sorry but I'm up to my ears in other things and I don't really have the capacity to discuss the finer points of the OpenAPI spec... Hit me up during a dev chat and we can chat...

Sorry

**Comment by pondermatic** [comment]
There's no need for you to do anything. That's why I closed the issue. I was mainly documenting the issue and what I found in case anybody (including me) runs into it in the future.

What I should next is:

- Open an issue in the [OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification) project asking for clarification on how `allOf` should behave when property fields are defined multiple times.
- Open an issue in the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project asking that the `description` field be extended the way the `default` field is.
- Open an issue in the [NSawg](https://github.com/RicoSuter/NSwag) project asking that support for multiple property definitions be added.
