### ISSUE TITLE
Delete student enrollment requires change to enrollment status

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms-rest#95]
If a `DELETE /students/{id}/enrollments/{post_id}` operation is performed on a membership enrollment with a status of `enrolled`, the student report page still displays a membership but with a blank status and enrolled column. If a `PATCH /students/{id}/enrollments/{post_id}` operation changes the `status` to `cancelled` before the `DELETE` operation, the enrollment is correctly removed from the student report page.

@eri-trabiccolo suggests two posibilities:
1. we check the enrollment status before deleting and if active we return an error with instructions on what to do before
1. always unenroll before deleting

Another option is:
3. Add a note to the `DELETE /students/{id}/enrollments/{post_id}` spec about the need to change the enrollment status first.

**Comment by eri-trabiccolo** [comment]
I think 3. should be along with 1. if we choose 1. as solution.
I don't think we should allow producing inconsitent data with our api :D.
What do you think?!

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

From [Slack in `#developers`](https://lifterlms.slack.com/archives/CCESQHE82/p1569502291119300):

> At the moment this is not 100% consistent with the process in wp-admin, because in that case you cannot delete an “active” enrollment, while in this case we can.

Under the hood `DELETE /students/{id}/enrollments/{post_id}` is using [`LLMS_Student::delete_ delete_enrollment`](https://developer.lifterlms.com/reference/classes/llms_student/delete_enrollment/)

I didn't set up an actual test case but it looks to me like this method should actually be removing all the enrollment data when it's executed. Is that not what's actually happening here?

I know the UI in the admin panel doesn't allow the deletion method to run without first cancelling the enrollment but it looks like the deletion method itself would still remove all the postmeta data properly.

What am I missing here?

**Comment by eri-trabiccolo** [comment]
Well it doesn't trigger some "unenrollment" action hooks + doesnt' do this:
https://github.com/gocodebox/lifterlms/blob/master/includes/models/model.llms.student.php#L1568

**Comment by eri-trabiccolo** [comment]
Also we have another thing to maybe take into account:
When *deleting* an enrollment from the order metabox we also set that order status to `cancelled`.
So I guess that, for consistency, we should do the same here... 
We should get the current trigger of the enrollment being deleted, and if it's an existing order we should also set this order status to `cancelled`, right?!

**Comment by thomasplevy** [comment]
Okay thanks!

The idea behind making only non-active enrollments deletable is that I don't want admins to have any confusion around the difference between deleting and unenrolling. I think it makes sense to maintain consistency in the API but I also want to reduce the complexity of developing applications. If we enforce this same design on the API it requires 2 api calls to do what it feels like should be possible with only one.

So I think we should do suggestions 1 & 2 AND add a `force` (bool) parameter to the `DELETE` method on the API.

So:

1. Check the enrollment status before deleting and if active and `force` is not set `true` an error will be returned. "Only non-active enrollments can be deleted blah blah blah"
2. If `force` is true perform an unenrollment if the current status is active and then delete in the same request.

In this way we can maintain the same design strategy as the admin panel while still allowing integrations to reduce API requests where appropriate.

@pondermatic and @eri-trabiccolo do either see issues with this strategy?

**Comment by thomasplevy** [comment]
> Also we have another thing to maybe take into account:
> When _deleting_ an enrollment from the order metabox we also set that order status to `cancelled`.
> So I guess that, for consistency, we should do the same here...
> We should get the current trigger of the enrollment being deleted, and if it's an existing order we should also set this order status to `cancelled`, right?!

This is something that probably shouldn't be moved out of the metabox code and into the orders controller.

The order status should be updated automatically using the hook for the enrollment status change.

This way the REST API doesn't need to duplicate logic from the admin panel metabox handlers

**Comment by pondermatic** [comment]
I like the idea of adding a `force` parameter.

**Comment by eri-trabiccolo** [comment]
> > Also we have another thing to maybe take into account:
> > When _deleting_ an enrollment from the order metabox we also set that order status to `cancelled`.
> > So I guess that, for consistency, we should do the same here...
> > We should get the current trigger of the enrollment being deleted, and if it's an existing order we should also set this order status to `cancelled`, right?!
> 
> This is something that probably should~n't~ be moved out of the metabox code and into the orders controller.
> 
> The order status should be updated automatically using the hook for the enrollment status change.
> 
> This way the REST API doesn't need to duplicate logic from the admin panel metabox handlers

@thomasplevy 
I would love this but I don't think it's really easy to do right now, or better, it requires an additional query as far as I can see...

When deleting an enrollment with the REST API, we delete basically all the enrollment post metas related to a student ID and a product ID. 
We don't have any info on the trigger, so we first need to know what's the enrollment (current) trigger so that we can pass it to the action. Or we need to fire an action just before the (maybe) deletion occurs, and the callback will be responsible for querying... maybe the latter is not a good choice.

So if you agree I would go with the basic change here. The `'force'` param addition and the subsequent logic we discussed above.

Then I'll submit a PR in core that will implement the action triggering above.

**Comment by thomasplevy** [comment]
I think that means we should also add an (optional) "trigger" parameter to both creation/update/and deletion requests for enrollments, right? It's defaulting to "any" as the trigger under the hood but we should probably allow triggers to be specified during the request. Right?

**Comment by eri-trabiccolo** [comment]
Not sure, you say ok it's up to you if you don't pass the current trigger, and to know what is you should make another request... Ah no we don't return the enrollment trigger, so how a consumer can know it?
So we have to add this new prop. Right?

**Comment by thomasplevy** [comment]
Yes... we'll need to add a new property too.

**Comment by eri-trabiccolo** [comment]
While working at the resolution of this I've had the occasion to think a little more about the whole issue, and test the things in core a little more.
We're forgetting one thing (and I did when developed the enrollment deletion feature):
 when running a membership enrollment deletion, which presumably auto-enrolled the students in several courses, at the moment, is not deleting the student-course enrollment (see https://github.com/gocodebox/lifterlms/issues/952 I've proposed a simple solution there).
Once fixed this in core it will automatically fix the issue raised in the first place here.
So we don't need a 'force' param for the DELETE, won't make sense I guess...

We still want to have the trigger as a property and as a parameter though, because that's for a different "issue".

**Comment by thomasplevy** [comment]
@eri-trabiccolo good catch on https://github.com/gocodebox/lifterlms/issues/952 but I don't see how that issue caused what @pondermatic has raised in this issue.

**Comment by eri-trabiccolo** [comment]
Have to integrate that issue and you'll get.

**Comment by thomasplevy** [comment]
@eri-trabiccolo so we still need a solution to this issue then, right? I'm still thinking the `force` parameter is pretty okay as a solution but we need to unpack the whole trigger thing before we start reworking the spec to accommodate triggers.

**Comment by eri-trabiccolo** [comment]
Nope @thomasplevy
https://github.com/gocodebox/lifterlms/pull/953 fixes the `'force'` issue. Basically with https://github.com/gocodebox/lifterlms/pull/953 deleting an enrollment deletes everything related to that enrollment, because the core will do.
with https://github.com/gocodebox/lifterlms/pull/953 the `force` will be totally useless.

We just need to unpack the `trigger` thing (which could be a totally different issue).
Which anyways will be "marginal" in my thoughts, I mean it'll be just to better target changes, like:
'Delete this student/course enrollment, with this specific trigger', if trigger !== any.

The order 'cancellation' will be something the core will do, and that will happen regardless of the trigger param, because I plan to fire the action hook (the orders controller will react to) always passing the enrollment trigger: say you pass 'any' as trigger, I will still retrieve the original enrollment trigger and use that, that's what matters.
